---

- name: installing latex rpms
  dnf:
    name: "{{ latex_rpms }}"
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: installing latex deb
  apt:
    name: "{{ latex_debs }}"
    state: present
  become: true
  when: ansible_os_family == 'Debian'