---

- name: configure timezone
  timezone:
    name: "{{ timezone }}"
  become: yes

#- name: host file
#  copy:
#    src: hosts
#    dest: /etc/hosts
#    owner: root
#    group: root
#    mode: 0644
#    setype: net_conf_t

- name: create mount points
  file:
    path: "{{ item.value.dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    setype: 'mnt_t'
  become: yes
  with_dict:
    - "{{ filesystems }}"

- name: add fstab mount points
  lineinfile:
    path: /etc/fstab
    line: "UUID={{ item.value.fs_uuid }}  {{ item.value.dir }}  xfs   defaults,noauto,user  1 2"
  become: yes
  with_dict:
    - "{{ filesystems }}"

- name: define backgrounds
  copy:
    src: "{{ item }}"
    dest: /usr/share/gnome-background-properties/
    owner: root
    group: root
    mode: 0644
    setype: usr_t
  become: yes
  with_items:
    - "cernicalos-backgrounds.xml"

- name: copy xml background images
  copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/
    owner: root
    group: root
    mode: 0644
    setype: usr_t
  become: yes
  with_items:
    - "cernicalos.xml"

- name: copy background images
  copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/
    owner: root
    group: root
    mode: 0644
    setype: usr_t
  become: yes
  with_items:
    - "cernicalos.png"

- name: change default background image
  lineinfile:
    path: /usr/share/glib-2.0/schemas/10_org.gnome.desktop.background.fedora.gschema.override
    regexp: '^picture-uri='
    line: picture-uri='file:///usr/share/backgrounds/cernicalos.xml'
  become: yes

- name: compile gnome schemas
  shell: /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
  become: yes

- name: disable wayland
  copy:
    src: gdm-custom.conf
    dest: /etc/gdm/custom.conf
    owner: root
    group: root
    mode: 0644
    setype: xdm_etc_t
  become: yes
  when: ansible_os_family == 'RedHat'