---

- name: enable systemd services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "{{ systemd_services }}"

- name: disable systemd services
  systemd:
    name: "{{ item }}"
    enabled: no
    masked: no
  become: yes
  with_items:
    - "{{ disabled_services }}"
