---
- name: Packages installation
  vars:
    rpms:
      - vim
      - vim-latex
      - git
      - ctags
      - cscope
  dnf:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "RedHat"
  with_items: rpms
