---
  
- name: install common rpm packages
  dnf:
    name: "{{ common_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install bluetooth rpm packages
  dnf:
    name: "{{ bluetooth_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install dev rpm packages
  dnf:
    name: "{{ dev_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install pyenv rpm packages
  dnf:
    name: "{{ pyenv_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install gnome rpm packages
  dnf:
    name: "{{ gnome_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install office rpm packages
  dnf:
    name: "{{ office_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install webcam rpm packages
  dnf:
    name: "{{ webcam_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install printing rpms
  dnf:
    name: "{{ printing_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install httpd rpms
  dnf:
    name: "{{ httpd_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install rpmfusion gpg key
  dnf:
    name: "{{ rpmfusion_gpg_key }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install rpmfusion repository rpm
  dnf:
    name: "{{ rpmfusion_rpm }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install codec rpms
  dnf:
    name: "{{ codec_rpms }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'