---
  
- name: install common rpm packages
  dnf:
    name: "{{ common_rpms }}"
    state: present
  become: yes

- name: install dev rpm packages
  dnf:
    name: "{{ dev_rpms }}"
    state: present
  become: yes

- name: install gnome rpm packages
  dnf:
    name: "{{ gnome_rpms }}"
    state: present
  become: yes

- name: install office rpm packages
  dnf:
    name: "{{ office_rpms }}"
    state: present
  become: yes

- name: install webcam rpm packages
  dnf:
    name: "{{ webcam_rpms }}"
    state: present
  become: yes

- name: install printing rpms
  dnf:
    name: "{{ printing_rpms }}"
    state: present
  become: yes
