---
  
- name: install common rpm packages
  dnf:
    name: "{{ common_rpms }}"
    state: present

- name: install dev rpm packages
  dnf:
    name: "{{ dev_rpms }}"
    state: present

- name: install gnome rpm packages
  dnf:
    name: "{{ gnome_rpms }}"
    state: present

- name: install office rpm packages
  dnf:
    name: "{{ office_rpms }}"
    state: present

- name: configure rpm fussion
  dnf:
    name: "{{ rpmfusion_rpm }}"
    state: present
