---

os_user: 'jadebustos'

timezone: 'Europe/Madrid'

systemd_services: ['firewalld', 'cockpit']

rpmfusion_rpm: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-33.noarch.rpm'
rpmfusion_gpg_key: 'https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020'

common_rpms: ['ca-certificates', 'bind-utils', 'chrony', 'curl', 'vim', 'wget', 'telnet', 'net-tools', 'rsync', 'zsh', 'ftp', 'bash', 'bash-completion', 'mc', 'cockpit', 'cockpit-machines', 'cockpit-networkmanager', 'cockpit-packagekit', 'cockpit-selinux', 'cockpit-system', 'cockpit-ws']
printing_rpms: ['cups', 'libjpeg-devel', 'cups-devel', 'cups-devel', 'libusb1-devel', 'sane-backends-devel', 'avahi-devel', 'avahi-tools', 'net-snmp-devel', 'openssl-devel', 'python3-PyQt4', 'libtool', 'rpm-build', 'python3-notify2']
webcam_rpms: ['v4l-utils', 'cheese']
dev_rpms: ['git', 'go', 'automake']
gnome_rpms: ['virt-viewer', 'gnome-control-center', 'network-manager-applet', 'gnome-tweaks', 'gnome-abrt', 'gnome-system-monitor','gnome-getting-started-docs-es', 'gnome-backgrounds', 'gnome-backgrounds-extras', 'gnome-font-viewer', 'gnome-themes-standard', 'gnome-remote-desktop']
office_rpms: ['firefox', 'gedit', 'libreoffice-core', 'libreoffice-base', 'libreoffice-data', 'libreoffice-calc', 'libreoffice-impress', 'libreoffice-math', 'libreoffice-writer','libreoffice-draw','libreoffice-help-es','libreoffice-langpack-es', 'libreoffice-opensymbol-fonts', 'libreoffice-gtk3', 'libreoffice-pdfimport', 'libreoffice-filters', 'chromium', 'gimp', 'keepassx']

telegram_url: 'https://telegram.org/dl/desktop/linux'

filesystems:
  bckprimario:
    fs_uuid: '899a84e4-ee7e-4be7-8fa1-c9d201b4c927'
    dir: '/media/mainbackup '
  bcksecundario:
    fs_uuid: 'f5c8a595-59e0-4304-947c-678c14ef00a2'
    dir: '/media/work'

scripts_backup: 
  laptop:
    url: 'https://raw.githubusercontent.com/jadebustos/misc/master/backup/backup-laptop.sh'
    path: '/usr/local/bin/backup-laptop'
  mainbackup:
    url: 'https://raw.githubusercontent.com/jadebustos/misc/master/backup/backup-mainbackup.sh'
    path: '/usr/local/bin/backup-mainbackup'