---

- name: install virtualization packages
  dnf:
    name: "{{ kvm_rpms }}"
    state: present
  become: yes

- name: install cockpit packages
  dnf:
    name: "{{ cockpit_rpms }}"
    state: present
  become: yes