---

- name: harden sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { 'line': 'PermitRootLogin yes', 'state': 'absent'}
    - { 'line': 'PermitRootLogin no', 'state': 'present'}
    - { 'line': 'PermitRootLogin prohibit-password', 'state': 'present'}
    - { 'line': 'PubkeyAuthentication yes', 'state': 'present'}
    - { 'line': 'PasswordAuthentication yes', 'state': 'present'}
    - { 'line': 'PermitEmptyPasswords no', 'state': 'present'}

- name: restart sshd service
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes