---

- name: install software (work laptop)
  hosts: all
  vars_files:
    - "group_vars/general.yaml"
    - "group_vars/vpn.yaml"
    - "group_vars/bind.yaml"
  gather_facts: true
  roles:
    - general
    - vcode
    - vpn
    - bind
