---

- name: install software (work laptop)
  hosts: all
  vars_files:
    - "group_vars/general.yaml"
    - "group_vars/latex.yaml"
    - "group_vars/vpn.yaml"
    - "group_vars/bind.yaml"
    - "group_vars/customca.yaml"  
  gather_facts: true
  roles:
    # - general
    #- latex
    # - vcode
    - vpn
    # - bind
    # - customca
