---

- name: install software (work laptop)
  hosts: all
  vars_files:
    - "group_vars/bind.yaml"
    - "group_vars/customca.yaml"  
    - "group_vars/general.yaml"
    - "group_vars/vpn.yaml"
  gather_facts: true
  roles:
    - general
    # - vcode
    # - vpn
    # - bind
    #- customca
