---

- name: "Passwordless sudo for user"
  remote_user: root
  hosts: all
  gather_facts: False
  vars_files:
    - group_vars/passwordless-sudo-vars.yml

  tasks:
    - name: "Configurging passwordless sudo for user"
      template:
        src: templates/passwordless-sudo.j2
        dest: /etc/sudoers.d/{{ user }}
        owner: root
        group: root
        mode: u=r,g=r,o=
